steps:
- id: 'branch name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$BRANCH_NAME"
      echo "***********************"
## [START tf-init]
- id: 'tf init'
  name: 'hashicorp/terraform:0.12.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      cd environments/$BRANCH_NAME
      terraform init
## [END tf-init]

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:0.12.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/$BRANCH_NAME
      terraform plan
## [END tf-plan]

## [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:0.12.9'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      cd environments/$BRANCH_NAME      
      terraform apply -auto-approve
## [END tf-apply]      